### ISSUE TITLE
What is needed to see a diff?

### ISSUE THREAD

**Issue by t184256** [aznhe21/actions-preview.nvim#5]
I get action descriptions where I'd expect to see a diff:

```
╭──────────────────────────── Code Action Preview ─────────────────────────────╮
│Command: Inline method/variable/parameter (pylsp_rope.refactor.inline)        │
```

This is the case for both telescope and nui backends.
Am I missing some configuration step?

**Comment by aznhe21** [comment]
Unfortunately, some Language Servers (including pylsp_rope in this case) realize Code Actions by means of [Command], which can perform any operation, instead of [TextEdit], which notifies text changes. In these Language Servers, we cannot get the result of text changes by a Code Action, and as a result, we cannot compute and display diffs.

Well, it's hard to read this from the UI, and I'll add it to the README later.

[TextEdit]: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit
[Command]: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#command
